In [2]:
import numpy as np
data = np.random.random((4,3)) * 10
print(data)

[[2.12789107 2.97804529 3.56893703]
 [3.1516656  8.56182627 6.74379528]
 [5.64375529 1.12544128 5.06258419]
 [5.92458204 9.26895152 5.80575929]]


In [7]:
data = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
data.max(axis=1)
data.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])